[package]
name = "customs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["cargo"] }
git2 = "0.18.2"
inline_colorization = "0.1.6"
toml = "0.8.11"
